version: "3.9"

name: refahi_stage

services:
  stage_notif:
    image: ghcr.io/refahigroup/refahi-notif:stage
    container_name: stage_notif
    networks:
      - refahi_stage_net
    restart: always
    environment:
      TZ: "Asia/Tehran"
      ASPNETCORE_ENVIRONMENT: "Staging"
      DB_USER: "${REFAHI_STAGE_NOTIF_DB_USER}"
      DB_PASSWORD: "${REFAHI_STAGE_NOTIF_DB_PASSWORD}"  
      JWT_KEY: "${REFAHI_STAGE_NOTIF_JWT_KEY}"
      SMS_API_KEY: "${REFAHI_STAGE_NOTIF_SMS_API_KEY}"
      EMAIL_TOKEN: "${REFAHI_STAGE_NOTIF_EMAIL_TOKEN}"         
      
networks:
  refahi_stage_net:
    external: true